export const carBrands = {
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "e-tron", "e-tron GT", "TT", "R8"],
  "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "Série 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "iX", "i4", "i5", "i7", "iX1", "iX3"],
  "Chery": ["Tiggo 2 Pro", "Tiggo 4 Pro", "Tiggo 7 Pro", "Tiggo 8 Pro"],
  "Citroën": ["C3", "C3 Aircross", "C4", "C4 X", "C5 Aircross", "C5 X", "Berlingo", "Ami", "Spacetourer", "Jumpy"],
  "Cupra": ["Leon", "Ateca", "Formentor", "Born"],
  "Dacia": ["Duster", "Sandero", "Sandero Stepway", "Logan", "Dokker", "Spring", "Jogger"],
  "DS": ["DS 3", "DS 4", "DS 7", "DS 9"],
  "Fiat": ["500", "500e", "500X", "500L", "Panda", "Tipo", "Doblo", "Ducato", "Punto", "Scudo"],
  "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "Mustang", "Mustang Mach-E", "Explorer", "Ranger", "Tourneo Connect", "Transit"],
  "Honda": ["Jazz", "Civic", "HR-V", "CR-V", "e:Ny1"],
  "Hyundai": ["i10", "i20", "i30", "Bayon", "Kona", "Tucson", "Santa Fe", "Ioniq 5", "Ioniq 6", "Staria", "Creta"],
  "Jaguar": ["XE", "XF", "E-Pace", "F-Pace", "I-Pace", "F-Type"],
  "Jeep": ["Renegade", "Compass", "Wrangler", "Avenger", "Grand Cherokee"],
  "Kia": ["Picanto", "Rio", "Ceed", "ProCeed", "XCeed", "Stonic", "Niro", "Sportage", "Seltos", "Sorento", "EV6", "EV9"],
  "Land Rover": ["Range Rover Evoque", "Range Rover Velar", "Range Rover Sport", "Range Rover", "Discovery Sport", "Discovery", "Defender"],
  "Lexus": ["UX", "NX", "RX", "RZ", "ES", "LS", "LC"],
  "Maserati": ["Ghibli", "Levante", "Grecale", "MC20"],
  "Mazda": ["Mazda2", "Mazda3", "CX-30", "CX-5", "CX-60", "MX-5"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "EQA", "EQB", "EQC", "EQE", "EQS", "Vito", "Citan", "Sprinter", "AMG GT"],
  "MG": ["MG4", "MG5", "ZS", "HS", "Marvel R"],
  "Mini": ["Cooper 3-portes", "Cooper 5-portes", "Cabrio", "Clubman", "Countryman"],
  "Mitsubishi": ["Space Star", "ASX", "Eclipse Cross"],
  "Nissan": ["Micra", "Juke", "Qashqai", "X-Trail", "Ariya", "Leaf", "Townstar"],
  "Opel": ["Corsa", "Astra", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro"],
  "Peugeot": ["108", "208", "2008", "301", "308", "3008", "408", "508", "5008", "Rifter", "Partner", "Expert", "Boxer"],
  "Porsche": ["718", "911", "Taycan", "Panamera", "Macan", "Cayenne"],
  "Renault": ["Twingo", "Clio", "Zoe", "Captur", "Megane", "Megane E-Tech", "Arkana", "Austral", "Kadjar", "Scenic E-Tech", "Espace", "Trafic", "Master", "Kangoo", "Express", "Symbol", "Fluence"],
  "Seat": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"],
  "Skoda": ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  "SsangYong": ["Tivoli", "Korando", "Rexton"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback"],
  "Suzuki": ["Ignis", "Swift", "Vitara", "S-Cross", "Jimny", "Across"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
  "Toyota": ["Aygo X", "Yaris", "Yaris Cross", "Corolla", "C-HR", "RAV4", "bZ4X", "Hilux", "Land Cruiser", "Proace City", "Proace"],
  "Volkswagen": ["Polo", "Golf", "T-Cross", "Taigo", "T-Roc", "Tiguan", "Passat", "Arteon", "Touran", "ID.3", "ID.4", "ID.5", "ID. Buzz", "Caddy", "Multivan", "Crafter"],
  "Volvo": ["S60", "V60", "S90", "V90", "XC40", "C40", "XC60", "XC90", "EX30", "EX90"]
} as const;

export type CarBrand = keyof typeof carBrands;
